SELECT * FROM LIBROS;
SELECT * FROM EDITORIALES;
DELETE FROM EDITORIALES WHERE idEditorial = 4;

DROP TRIGGER trBorraLibros;
-- CREACION DEL TRIGGER --
DELIMITER $$
CREATE TRIGGER trBorraLibros
BEFORE DELETE ON Editoriales
FOR EACH ROW
BEGIN
	DELETE FROM LIBROS WHERE idEditorial = OLD.idEditorial;
END $$