SELECT * FROM LIBROS;
SELECT * FROM EDITORIALES;
DELETE FROM EDITORIALES WHERE idEditorial = 4;

DROP TRIGGER trBorraLibros;
-- CREACION DEL TRIGGER --
DELIMITER $$
CREATE TRIGGER trBorraLibros
BEFORE DELETE ON Editoriales
FOR EACH ROW
BEGIN
	DELETE FROM LIBROS WHERE idEditorial = OLD.idEditorial;
END $$





-- TRIGGER DE BITACORA PARA CUIDAR CAMBIOS EN EL PRECIO DE LOS LIBROS
DELIMITER $$
CREATE TRIGGER trCambiosLibros
AFTER UPDATE ON LIBROS
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA_LIBROS VALUES (NULL, NEW.idLibro, OLD.Titulo, OLD.precio, NEW.precio, USER(), NOW() );
END $$

UPDATE LIBROS SET precio = 170 WHERE idLibro = 1 $$

SELECT * FROM BITACORA_LIBROS;